name: Build and Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the source code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 14.15.x

      - name: Add Yarn Global Binary path to PATH
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
        run:
          echo "::add-path::$(yarn global bin)"

      - name: Setup elm environment
        uses: justgook/setup-elm@1.2.0
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
        with:
          elm-version: 0.19.1

      - name: Install dependencies
        run: make dep && which uglifyjs

      - name: Copy static assets
        run: make build/copy

      - name: Build the application
        run: make build/dist
      
      - name: Deploy the application
        uses: peaceiris/actions-gh-pages@v3
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dst
        
        
